#!/usr/bin/with-contenv bash

# cleanup pid if it exists
[[ -e /config/rtdclient.pid ]] && \
	rm -rf /config/rtdclient.pid

[[ -e /data/rtdclient.pid ]] && \
	rm -rf /data/rtdclient.pid

# permissions
echo "Setting permissions"

if [ ! -w /data/db ]; then
  echo "[init] Fixing /data/db ownership..."
  chown -R abc:abc /data/db
fi

if [ ! -w /data/downloads ]; then
  echo "[init] Fixing /data/downloads ownership..."
  chown abc:abc /data/downloads
fi
