name: Docker Image CI

on:
  workflow_dispatch:       
  push:
    tags:
      - v*

permissions: 
  packages: write
  
env:
  APP_NAME: rdtclient
  DOCKER_FILE: ./Dockerfile
  DOCKER_PLATFORMS: "linux/arm64/v8,linux/amd64"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Docker Metadata action
      id: meta
      uses: docker/metadata-action@v4.3.0
      with:
        images: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}
        tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v2.1.0
    
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.5.0
      with:
        buildkitd-flags: --debug
    
    - name: Docker Login
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        file: ${{ env.DOCKER_FILE }}
        platforms: ${{ env.DOCKER_PLATFORMS }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Docker Hub Registry Description
      uses: peter-evans/dockerhub-description@v3.3.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}
        short-description: |
          A web interface to manage your torrents on Real-Debrid, AllDebrid, Premiumize, or TorBox.
        readme-filepath: ./README-DOCKER.md
